// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service-ledger.proto

package io.dazraf.ledger;

public final class ServiceLedger {
  private ServiceLedger() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AmountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.dazraf.ledger.Amount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool negative = 1;</code>
     */
    boolean getNegative();

    /**
     * <code>uint64 pounds = 2;</code>
     */
    long getPounds();

    /**
     * <code>uint32 pence = 3;</code>
     */
    int getPence();
  }
  /**
   * Protobuf type {@code io.dazraf.ledger.Amount}
   */
  public  static final class Amount extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.dazraf.ledger.Amount)
      AmountOrBuilder {
    // Use Amount.newBuilder() to construct.
    private Amount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Amount() {
      negative_ = false;
      pounds_ = 0L;
      pence_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Amount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              negative_ = input.readBool();
              break;
            }
            case 16: {

              pounds_ = input.readUInt64();
              break;
            }
            case 24: {

              pence_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.dazraf.ledger.ServiceLedger.internal_static_io_dazraf_ledger_Amount_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.dazraf.ledger.ServiceLedger.internal_static_io_dazraf_ledger_Amount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.dazraf.ledger.ServiceLedger.Amount.class, io.dazraf.ledger.ServiceLedger.Amount.Builder.class);
    }

    public static final int NEGATIVE_FIELD_NUMBER = 1;
    private boolean negative_;
    /**
     * <code>bool negative = 1;</code>
     */
    public boolean getNegative() {
      return negative_;
    }

    public static final int POUNDS_FIELD_NUMBER = 2;
    private long pounds_;
    /**
     * <code>uint64 pounds = 2;</code>
     */
    public long getPounds() {
      return pounds_;
    }

    public static final int PENCE_FIELD_NUMBER = 3;
    private int pence_;
    /**
     * <code>uint32 pence = 3;</code>
     */
    public int getPence() {
      return pence_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (negative_ != false) {
        output.writeBool(1, negative_);
      }
      if (pounds_ != 0L) {
        output.writeUInt64(2, pounds_);
      }
      if (pence_ != 0) {
        output.writeUInt32(3, pence_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (negative_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, negative_);
      }
      if (pounds_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, pounds_);
      }
      if (pence_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, pence_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.dazraf.ledger.ServiceLedger.Amount)) {
        return super.equals(obj);
      }
      io.dazraf.ledger.ServiceLedger.Amount other = (io.dazraf.ledger.ServiceLedger.Amount) obj;

      boolean result = true;
      result = result && (getNegative()
          == other.getNegative());
      result = result && (getPounds()
          == other.getPounds());
      result = result && (getPence()
          == other.getPence());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NEGATIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNegative());
      hash = (37 * hash) + POUNDS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPounds());
      hash = (37 * hash) + PENCE_FIELD_NUMBER;
      hash = (53 * hash) + getPence();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.dazraf.ledger.ServiceLedger.Amount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.dazraf.ledger.ServiceLedger.Amount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.dazraf.ledger.ServiceLedger.Amount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.dazraf.ledger.ServiceLedger.Amount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.dazraf.ledger.ServiceLedger.Amount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.dazraf.ledger.ServiceLedger.Amount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.dazraf.ledger.ServiceLedger.Amount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.dazraf.ledger.ServiceLedger.Amount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.dazraf.ledger.ServiceLedger.Amount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.dazraf.ledger.ServiceLedger.Amount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.dazraf.ledger.ServiceLedger.Amount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.dazraf.ledger.Amount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.dazraf.ledger.Amount)
        io.dazraf.ledger.ServiceLedger.AmountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.dazraf.ledger.ServiceLedger.internal_static_io_dazraf_ledger_Amount_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.dazraf.ledger.ServiceLedger.internal_static_io_dazraf_ledger_Amount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.dazraf.ledger.ServiceLedger.Amount.class, io.dazraf.ledger.ServiceLedger.Amount.Builder.class);
      }

      // Construct using io.dazraf.ledger.ServiceLedger.Amount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        negative_ = false;

        pounds_ = 0L;

        pence_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.dazraf.ledger.ServiceLedger.internal_static_io_dazraf_ledger_Amount_descriptor;
      }

      public io.dazraf.ledger.ServiceLedger.Amount getDefaultInstanceForType() {
        return io.dazraf.ledger.ServiceLedger.Amount.getDefaultInstance();
      }

      public io.dazraf.ledger.ServiceLedger.Amount build() {
        io.dazraf.ledger.ServiceLedger.Amount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.dazraf.ledger.ServiceLedger.Amount buildPartial() {
        io.dazraf.ledger.ServiceLedger.Amount result = new io.dazraf.ledger.ServiceLedger.Amount(this);
        result.negative_ = negative_;
        result.pounds_ = pounds_;
        result.pence_ = pence_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.dazraf.ledger.ServiceLedger.Amount) {
          return mergeFrom((io.dazraf.ledger.ServiceLedger.Amount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.dazraf.ledger.ServiceLedger.Amount other) {
        if (other == io.dazraf.ledger.ServiceLedger.Amount.getDefaultInstance()) return this;
        if (other.getNegative() != false) {
          setNegative(other.getNegative());
        }
        if (other.getPounds() != 0L) {
          setPounds(other.getPounds());
        }
        if (other.getPence() != 0) {
          setPence(other.getPence());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.dazraf.ledger.ServiceLedger.Amount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.dazraf.ledger.ServiceLedger.Amount) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean negative_ ;
      /**
       * <code>bool negative = 1;</code>
       */
      public boolean getNegative() {
        return negative_;
      }
      /**
       * <code>bool negative = 1;</code>
       */
      public Builder setNegative(boolean value) {
        
        negative_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool negative = 1;</code>
       */
      public Builder clearNegative() {
        
        negative_ = false;
        onChanged();
        return this;
      }

      private long pounds_ ;
      /**
       * <code>uint64 pounds = 2;</code>
       */
      public long getPounds() {
        return pounds_;
      }
      /**
       * <code>uint64 pounds = 2;</code>
       */
      public Builder setPounds(long value) {
        
        pounds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 pounds = 2;</code>
       */
      public Builder clearPounds() {
        
        pounds_ = 0L;
        onChanged();
        return this;
      }

      private int pence_ ;
      /**
       * <code>uint32 pence = 3;</code>
       */
      public int getPence() {
        return pence_;
      }
      /**
       * <code>uint32 pence = 3;</code>
       */
      public Builder setPence(int value) {
        
        pence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 pence = 3;</code>
       */
      public Builder clearPence() {
        
        pence_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:io.dazraf.ledger.Amount)
    }

    // @@protoc_insertion_point(class_scope:io.dazraf.ledger.Amount)
    private static final io.dazraf.ledger.ServiceLedger.Amount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.dazraf.ledger.ServiceLedger.Amount();
    }

    public static io.dazraf.ledger.ServiceLedger.Amount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Amount>
        PARSER = new com.google.protobuf.AbstractParser<Amount>() {
      public Amount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Amount(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Amount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Amount> getParserForType() {
      return PARSER;
    }

    public io.dazraf.ledger.ServiceLedger.Amount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LedgerNotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.dazraf.ledger.LedgerNotification)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string fromAccountId = 1;</code>
     */
    java.lang.String getFromAccountId();
    /**
     * <code>string fromAccountId = 1;</code>
     */
    com.google.protobuf.ByteString
        getFromAccountIdBytes();

    /**
     * <code>string toAccountId = 2;</code>
     */
    java.lang.String getToAccountId();
    /**
     * <code>string toAccountId = 2;</code>
     */
    com.google.protobuf.ByteString
        getToAccountIdBytes();

    /**
     * <code>.io.dazraf.ledger.Amount amount = 3;</code>
     */
    boolean hasAmount();
    /**
     * <code>.io.dazraf.ledger.Amount amount = 3;</code>
     */
    io.dazraf.ledger.ServiceLedger.Amount getAmount();
    /**
     * <code>.io.dazraf.ledger.Amount amount = 3;</code>
     */
    io.dazraf.ledger.ServiceLedger.AmountOrBuilder getAmountOrBuilder();
  }
  /**
   * Protobuf type {@code io.dazraf.ledger.LedgerNotification}
   */
  public  static final class LedgerNotification extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.dazraf.ledger.LedgerNotification)
      LedgerNotificationOrBuilder {
    // Use LedgerNotification.newBuilder() to construct.
    private LedgerNotification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LedgerNotification() {
      fromAccountId_ = "";
      toAccountId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LedgerNotification(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              fromAccountId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              toAccountId_ = s;
              break;
            }
            case 26: {
              io.dazraf.ledger.ServiceLedger.Amount.Builder subBuilder = null;
              if (amount_ != null) {
                subBuilder = amount_.toBuilder();
              }
              amount_ = input.readMessage(io.dazraf.ledger.ServiceLedger.Amount.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(amount_);
                amount_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.dazraf.ledger.ServiceLedger.internal_static_io_dazraf_ledger_LedgerNotification_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.dazraf.ledger.ServiceLedger.internal_static_io_dazraf_ledger_LedgerNotification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.dazraf.ledger.ServiceLedger.LedgerNotification.class, io.dazraf.ledger.ServiceLedger.LedgerNotification.Builder.class);
    }

    public static final int FROMACCOUNTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object fromAccountId_;
    /**
     * <code>string fromAccountId = 1;</code>
     */
    public java.lang.String getFromAccountId() {
      java.lang.Object ref = fromAccountId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromAccountId_ = s;
        return s;
      }
    }
    /**
     * <code>string fromAccountId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFromAccountIdBytes() {
      java.lang.Object ref = fromAccountId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromAccountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOACCOUNTID_FIELD_NUMBER = 2;
    private volatile java.lang.Object toAccountId_;
    /**
     * <code>string toAccountId = 2;</code>
     */
    public java.lang.String getToAccountId() {
      java.lang.Object ref = toAccountId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toAccountId_ = s;
        return s;
      }
    }
    /**
     * <code>string toAccountId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getToAccountIdBytes() {
      java.lang.Object ref = toAccountId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toAccountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private io.dazraf.ledger.ServiceLedger.Amount amount_;
    /**
     * <code>.io.dazraf.ledger.Amount amount = 3;</code>
     */
    public boolean hasAmount() {
      return amount_ != null;
    }
    /**
     * <code>.io.dazraf.ledger.Amount amount = 3;</code>
     */
    public io.dazraf.ledger.ServiceLedger.Amount getAmount() {
      return amount_ == null ? io.dazraf.ledger.ServiceLedger.Amount.getDefaultInstance() : amount_;
    }
    /**
     * <code>.io.dazraf.ledger.Amount amount = 3;</code>
     */
    public io.dazraf.ledger.ServiceLedger.AmountOrBuilder getAmountOrBuilder() {
      return getAmount();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFromAccountIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fromAccountId_);
      }
      if (!getToAccountIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, toAccountId_);
      }
      if (amount_ != null) {
        output.writeMessage(3, getAmount());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFromAccountIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fromAccountId_);
      }
      if (!getToAccountIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, toAccountId_);
      }
      if (amount_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getAmount());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.dazraf.ledger.ServiceLedger.LedgerNotification)) {
        return super.equals(obj);
      }
      io.dazraf.ledger.ServiceLedger.LedgerNotification other = (io.dazraf.ledger.ServiceLedger.LedgerNotification) obj;

      boolean result = true;
      result = result && getFromAccountId()
          .equals(other.getFromAccountId());
      result = result && getToAccountId()
          .equals(other.getToAccountId());
      result = result && (hasAmount() == other.hasAmount());
      if (hasAmount()) {
        result = result && getAmount()
            .equals(other.getAmount());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROMACCOUNTID_FIELD_NUMBER;
      hash = (53 * hash) + getFromAccountId().hashCode();
      hash = (37 * hash) + TOACCOUNTID_FIELD_NUMBER;
      hash = (53 * hash) + getToAccountId().hashCode();
      if (hasAmount()) {
        hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getAmount().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.dazraf.ledger.ServiceLedger.LedgerNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.dazraf.ledger.ServiceLedger.LedgerNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.dazraf.ledger.ServiceLedger.LedgerNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.dazraf.ledger.ServiceLedger.LedgerNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.dazraf.ledger.ServiceLedger.LedgerNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.dazraf.ledger.ServiceLedger.LedgerNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.dazraf.ledger.ServiceLedger.LedgerNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.dazraf.ledger.ServiceLedger.LedgerNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.dazraf.ledger.ServiceLedger.LedgerNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.dazraf.ledger.ServiceLedger.LedgerNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.dazraf.ledger.ServiceLedger.LedgerNotification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.dazraf.ledger.LedgerNotification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.dazraf.ledger.LedgerNotification)
        io.dazraf.ledger.ServiceLedger.LedgerNotificationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.dazraf.ledger.ServiceLedger.internal_static_io_dazraf_ledger_LedgerNotification_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.dazraf.ledger.ServiceLedger.internal_static_io_dazraf_ledger_LedgerNotification_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.dazraf.ledger.ServiceLedger.LedgerNotification.class, io.dazraf.ledger.ServiceLedger.LedgerNotification.Builder.class);
      }

      // Construct using io.dazraf.ledger.ServiceLedger.LedgerNotification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        fromAccountId_ = "";

        toAccountId_ = "";

        if (amountBuilder_ == null) {
          amount_ = null;
        } else {
          amount_ = null;
          amountBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.dazraf.ledger.ServiceLedger.internal_static_io_dazraf_ledger_LedgerNotification_descriptor;
      }

      public io.dazraf.ledger.ServiceLedger.LedgerNotification getDefaultInstanceForType() {
        return io.dazraf.ledger.ServiceLedger.LedgerNotification.getDefaultInstance();
      }

      public io.dazraf.ledger.ServiceLedger.LedgerNotification build() {
        io.dazraf.ledger.ServiceLedger.LedgerNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.dazraf.ledger.ServiceLedger.LedgerNotification buildPartial() {
        io.dazraf.ledger.ServiceLedger.LedgerNotification result = new io.dazraf.ledger.ServiceLedger.LedgerNotification(this);
        result.fromAccountId_ = fromAccountId_;
        result.toAccountId_ = toAccountId_;
        if (amountBuilder_ == null) {
          result.amount_ = amount_;
        } else {
          result.amount_ = amountBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.dazraf.ledger.ServiceLedger.LedgerNotification) {
          return mergeFrom((io.dazraf.ledger.ServiceLedger.LedgerNotification)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.dazraf.ledger.ServiceLedger.LedgerNotification other) {
        if (other == io.dazraf.ledger.ServiceLedger.LedgerNotification.getDefaultInstance()) return this;
        if (!other.getFromAccountId().isEmpty()) {
          fromAccountId_ = other.fromAccountId_;
          onChanged();
        }
        if (!other.getToAccountId().isEmpty()) {
          toAccountId_ = other.toAccountId_;
          onChanged();
        }
        if (other.hasAmount()) {
          mergeAmount(other.getAmount());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.dazraf.ledger.ServiceLedger.LedgerNotification parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.dazraf.ledger.ServiceLedger.LedgerNotification) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object fromAccountId_ = "";
      /**
       * <code>string fromAccountId = 1;</code>
       */
      public java.lang.String getFromAccountId() {
        java.lang.Object ref = fromAccountId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromAccountId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fromAccountId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFromAccountIdBytes() {
        java.lang.Object ref = fromAccountId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromAccountId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fromAccountId = 1;</code>
       */
      public Builder setFromAccountId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromAccountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fromAccountId = 1;</code>
       */
      public Builder clearFromAccountId() {
        
        fromAccountId_ = getDefaultInstance().getFromAccountId();
        onChanged();
        return this;
      }
      /**
       * <code>string fromAccountId = 1;</code>
       */
      public Builder setFromAccountIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromAccountId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object toAccountId_ = "";
      /**
       * <code>string toAccountId = 2;</code>
       */
      public java.lang.String getToAccountId() {
        java.lang.Object ref = toAccountId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toAccountId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string toAccountId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getToAccountIdBytes() {
        java.lang.Object ref = toAccountId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toAccountId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string toAccountId = 2;</code>
       */
      public Builder setToAccountId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toAccountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string toAccountId = 2;</code>
       */
      public Builder clearToAccountId() {
        
        toAccountId_ = getDefaultInstance().getToAccountId();
        onChanged();
        return this;
      }
      /**
       * <code>string toAccountId = 2;</code>
       */
      public Builder setToAccountIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toAccountId_ = value;
        onChanged();
        return this;
      }

      private io.dazraf.ledger.ServiceLedger.Amount amount_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.dazraf.ledger.ServiceLedger.Amount, io.dazraf.ledger.ServiceLedger.Amount.Builder, io.dazraf.ledger.ServiceLedger.AmountOrBuilder> amountBuilder_;
      /**
       * <code>.io.dazraf.ledger.Amount amount = 3;</code>
       */
      public boolean hasAmount() {
        return amountBuilder_ != null || amount_ != null;
      }
      /**
       * <code>.io.dazraf.ledger.Amount amount = 3;</code>
       */
      public io.dazraf.ledger.ServiceLedger.Amount getAmount() {
        if (amountBuilder_ == null) {
          return amount_ == null ? io.dazraf.ledger.ServiceLedger.Amount.getDefaultInstance() : amount_;
        } else {
          return amountBuilder_.getMessage();
        }
      }
      /**
       * <code>.io.dazraf.ledger.Amount amount = 3;</code>
       */
      public Builder setAmount(io.dazraf.ledger.ServiceLedger.Amount value) {
        if (amountBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          amount_ = value;
          onChanged();
        } else {
          amountBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.io.dazraf.ledger.Amount amount = 3;</code>
       */
      public Builder setAmount(
          io.dazraf.ledger.ServiceLedger.Amount.Builder builderForValue) {
        if (amountBuilder_ == null) {
          amount_ = builderForValue.build();
          onChanged();
        } else {
          amountBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.io.dazraf.ledger.Amount amount = 3;</code>
       */
      public Builder mergeAmount(io.dazraf.ledger.ServiceLedger.Amount value) {
        if (amountBuilder_ == null) {
          if (amount_ != null) {
            amount_ =
              io.dazraf.ledger.ServiceLedger.Amount.newBuilder(amount_).mergeFrom(value).buildPartial();
          } else {
            amount_ = value;
          }
          onChanged();
        } else {
          amountBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.io.dazraf.ledger.Amount amount = 3;</code>
       */
      public Builder clearAmount() {
        if (amountBuilder_ == null) {
          amount_ = null;
          onChanged();
        } else {
          amount_ = null;
          amountBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.io.dazraf.ledger.Amount amount = 3;</code>
       */
      public io.dazraf.ledger.ServiceLedger.Amount.Builder getAmountBuilder() {
        
        onChanged();
        return getAmountFieldBuilder().getBuilder();
      }
      /**
       * <code>.io.dazraf.ledger.Amount amount = 3;</code>
       */
      public io.dazraf.ledger.ServiceLedger.AmountOrBuilder getAmountOrBuilder() {
        if (amountBuilder_ != null) {
          return amountBuilder_.getMessageOrBuilder();
        } else {
          return amount_ == null ?
              io.dazraf.ledger.ServiceLedger.Amount.getDefaultInstance() : amount_;
        }
      }
      /**
       * <code>.io.dazraf.ledger.Amount amount = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.dazraf.ledger.ServiceLedger.Amount, io.dazraf.ledger.ServiceLedger.Amount.Builder, io.dazraf.ledger.ServiceLedger.AmountOrBuilder> 
          getAmountFieldBuilder() {
        if (amountBuilder_ == null) {
          amountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.dazraf.ledger.ServiceLedger.Amount, io.dazraf.ledger.ServiceLedger.Amount.Builder, io.dazraf.ledger.ServiceLedger.AmountOrBuilder>(
                  getAmount(),
                  getParentForChildren(),
                  isClean());
          amount_ = null;
        }
        return amountBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:io.dazraf.ledger.LedgerNotification)
    }

    // @@protoc_insertion_point(class_scope:io.dazraf.ledger.LedgerNotification)
    private static final io.dazraf.ledger.ServiceLedger.LedgerNotification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.dazraf.ledger.ServiceLedger.LedgerNotification();
    }

    public static io.dazraf.ledger.ServiceLedger.LedgerNotification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LedgerNotification>
        PARSER = new com.google.protobuf.AbstractParser<LedgerNotification>() {
      public LedgerNotification parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LedgerNotification(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LedgerNotification> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LedgerNotification> getParserForType() {
      return PARSER;
    }

    public io.dazraf.ledger.ServiceLedger.LedgerNotification getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_dazraf_ledger_Amount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_dazraf_ledger_Amount_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_dazraf_ledger_LedgerNotification_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_dazraf_ledger_LedgerNotification_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024service-ledger.proto\022\020io.dazraf.ledger" +
      "\032\013empty.proto\"9\n\006Amount\022\020\n\010negative\030\001 \001(" +
      "\010\022\016\n\006pounds\030\002 \001(\004\022\r\n\005pence\030\003 \001(\r\"j\n\022Ledg" +
      "erNotification\022\025\n\rfromAccountId\030\001 \001(\t\022\023\n" +
      "\013toAccountId\030\002 \001(\t\022(\n\006amount\030\003 \001(\0132\030.io." +
      "dazraf.ledger.Amount2g\n\rLedgerService\022V\n" +
      "\023LedgerNotifications\022\027.io.dazraf.ledger." +
      "Empty\032$.io.dazraf.ledger.LedgerNotificat" +
      "ion0\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.dazraf.ledger.EmptyProtos.getDescriptor(),
        }, assigner);
    internal_static_io_dazraf_ledger_Amount_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_dazraf_ledger_Amount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_dazraf_ledger_Amount_descriptor,
        new java.lang.String[] { "Negative", "Pounds", "Pence", });
    internal_static_io_dazraf_ledger_LedgerNotification_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_dazraf_ledger_LedgerNotification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_dazraf_ledger_LedgerNotification_descriptor,
        new java.lang.String[] { "FromAccountId", "ToAccountId", "Amount", });
    io.dazraf.ledger.EmptyProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
